# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d390463c344bec0bc3b68564d4a44b880706d3297d8d1e66ac210f69d29dcecad2f10e6bc3d83c4b9edbb1e4abfaa3510d7d20145afeca9c5098a4a697c01c82

test:
  secret_key_base: bcf81f4c2afb1804e1fb48b95c65bf5cdc018921d6720195e0dee9c60f66a7487aebe094bc735c8288b9b07e647ca3c4082c587b7db18811caf96be304db7e21

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
